### ISSUE TITLE
请问作者能否在源码中加入返回 敏感词及敏感词位置 的方法

### ISSUE THREAD

**Issue by jwzjay** [houbb/sensitive-word#11]

**Comment by houbb** [comment]
你可以看下 SensitiveWordBs 引导类，我没记错的话是有的。直接返回敏感词只是对结果的一种处理。如果没有，我后续加一下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jwzjay ***@***.***&gt;
发送时间: 2021年8月5日 17:23
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[houbb/sensitive-word] 请问作者能否在源码中加入返回 敏感词及敏感词位置 的方法 (#11)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jwzjay** [comment]
看了一下源码, 貌似是没有这个方法的,麻烦您有时间的话能否加一下,多谢了

**Comment by houbb** [comment]
v0.1.0 版本已支持，可以返回对应的下标信息。

**Comment by houbb** [comment]
V0.1.0 版本已经支持。

参考文档：[返回所有敏感词](https://github.com/houbb/sensitive-word/#%E8%BF%94%E5%9B%9E%E6%89%80%E6%9C%89%E6%95%8F%E6%84%9F%E8%AF%8D)

使用例子：

```java
final String text = "五星红旗迎风飘扬，毛主席的画像屹立在天安门前。";

List<IWordResult> wordList = SensitiveWordHelper.findAll(text, WordResultHandlers.raw());
Assert.assertEquals("[WordResult{word='五星红旗', startIndex=0, endIndex=4}, WordResult{word='毛主席', startIndex=9, endIndex=12}, WordResult{word='天安门', startIndex=18, endIndex=21}]", wordList.toString());
```
